Get-AppxPackage *XBox* | Remove-AppxPackage
Get-AppxPackage *OneDriveSync* | Remove-AppxPackage
Get-AppxPackage *People* | Remove-AppxPackage
Get-AppxPackage *Wallet* | Remove-AppxPackage
Get-AppxPackage *Weather* | Remove-AppxPackage
Get-AppxPackage *Advertising* | Remove-AppxPackage
Get-AppxPackage *Todos* | Remove-AppxPackage
Get-AppxPackage *OneNote* | Remove-AppxPackage
Get-AppxPackage *StickyNotes* | Remove-AppxPackage
Get-AppxPackage *Phone* | Remove-AppxPackage
Get-AppxPackage *Solitaire* | Remove-AppxPackage
Get-AppxPackage *PowerAutomate* | Remove-AppxPackage
Get-AppxPackage *MixedReality* | Remove-AppxPackage
Get-AppxPackage *Movies* | Remove-AppxPackage
Get-AppxPackage *Mail* | Remove-AppxPackage
Get-AppxPackage *GetHelp* | Remove-AppxPackage
Get-AppxPackage *Office* | Remove-AppxPackage
Get-AppxPackage *Paint3D* | Remove-AppxPackage
Get-AppxPackage *Tips* | Remove-AppxPackage
Get-AppxPackage *News* | Remove-AppxPackage
Get-AppxPackage *TikTok* | Remove-AppxPackage
Get-AppxPackage *Instagram* | Remove-AppxPackage
Get-AppxPackage *Netflix* | Remove-AppxPackage
Get-AppxPackage *PrimeVideo* | Remove-AppxPackage
Get-AppxPackage *Dropbox* | Remove-AppxPackage
Get-AppxPackage *Spotify* | Remove-AppxPackage
Get-AppxPackage *Teams* | Remove-AppxPackage
Get-AppxPackage *Maps* | Remove-AppxPackage
Get-AppxPackage *Cortana* | Remove-AppxPackage
Get-AppxPackage *Candy* | Remove-AppxPackage
Get-AppxPackage *Groove* | Remove-AppxPackage
Get-AppxPackage *Voice* | Remove-AppxPackage
Get-AppxPackage *Clipchamp* | Remove-AppxPackage
